### ISSUE TITLE
[SC067] Update candidate

### ISSUE THREAD

**Issue by nuon-neourng** [pnc-virtual-company/2018-selection#103]
For this task we need to be able to update candidates from the table which interact with database

**Comment by SopheakWEP** [comment]
Now I'm getting stuck with id

**Comment by SopheakWEP** [comment]
now I'm finished with get old value from database and next i will work on update new data to database

**Comment by SopheakWEP** [comment]
For update candidate, I decided to choose new database and I done with it

**Comment by nuon-neourng** [comment]
Very nice pheak well done.
