### ISSUE TITLE
[SC074]Create function sending email

### ISSUE THREAD

**Issue by nuon-neourng** [pnc-virtual-company/2018-selection#114]
You need to create a function for send an email to user who reset their password.

**Comment by SopheakWEP** [comment]
On this function I had done for send email but I'm not include into our project yet

**Comment by SopheakWEP** [comment]
on this function, I'm not sure we send an email when only create the new user or have other action

**Comment by dakhen-sok** [comment]
For this function, I already told you so we have 2 times when we create and reset password
