### ISSUE TITLE
[SC075]List the selected candidate from db by using AJAX

### ISSUE THREAD

**Issue by dakhen-sok** [pnc-virtual-company/2018-selection#121]
For this task we need to use the AJAX to get all data from the database.However we don't need to reload page either.

**Comment by dakhen-sok** [comment]
For this task I assign to vuthy but it is urgent and she is going to be late so I have to help her.Now I already finish it.So you all can check it.

**Comment by CheaChan** [comment]
I already tested on this task and change something error like ID Candidates and ID when we export as Excel.
