### ISSUE TITLE
[Teacher] Security not guaranteed: URL http://kratie.pnc.lan/2018vc2ga/c_candidates accessible when logout

### ISSUE THREAD

**Issue by matthieuderoo** [pnc-virtual-company/2018-selection#148]

**Comment by dakhen-sok** [comment]
I am working on this task.

**Comment by dakhen-sok** [comment]
For this task I already finish it, So you all can test it now.

**Comment by CheaChan** [comment]
I think it is acceptable for use because the user cannot access when they log out copy the URL past into our application.
