### ISSUE TITLE
[SC001] Validate Layout List of candidates #task 4

### ISSUE THREAD

**Issue by vuthypouk** [pnc-virtual-company/2018-selection#15]
please read and understand about the interface with the requirement  some point that you want to change

**Comment by nuon-neourng** [comment]
I think this list should be crud.

**Comment by dakhen-sok** [comment]
I think that this layout it is good , but it seem to be a bit confused for admin view and normal view. And for my idea I think this one it use for normal user and I think we need to add only one more button for export the list that this layout also related to the task 7 and it seem to be missing one fields the same to task number 7 also.

**Comment by nuon-neourng** [comment]
Yes so I suppose that it is for normal user we no need to crud and only add the button export below.

**Comment by dakhen-sok** [comment]
Yes of course, So I think that if we just add the export button below that is the great change for this task.because it also related to task 7
