### ISSUE TITLE
[Code Review] Missing comments

### ISSUE THREAD

**Issue by bbalet** [pnc-virtual-company/2018-selection#153]
Your code doesn't contain enough comments.
For example into https://github.com/pnc-virtual-company/2018-selection/blob/SC01/application/controllers/C_candidates.php

Few methods are commented. Above the functions, you should find a description of the purpose of the function.

**Comment by CheaChan** [comment]
I have comment almost all files in the application, so you can check it more if I have any missing you can correct it or add more comment in the application.
