### ISSUE TITLE
[SC004] Validate layout Export the list of selected candidates #task 7

### ISSUE THREAD

**Issue by vuthypouk** [pnc-virtual-company/2018-selection#17]
please read and understand about the interface with the requirement  some point that you want to change

**Comment by dakhen-sok** [comment]
I am not sure with this yet. because some part of the layout are not the same I can't decided. Anyways I need to add Export list button , which use for link to download or export the list out.

**Comment by nuon-neourng** [comment]
For me I think the export button should be below the datatable include admin and normal user because it easy to compare the data.
