### ISSUE TITLE
[SC085] function calculate automatically in home asset

### ISSUE THREAD

**Issue by CheaChan** [pnc-virtual-company/2018-selection#171]
This task for helping when we insert new candidates.

**Comment by CheaChan** [comment]
I have completed almost all, but I have a bit problem with the global total. So if you all free you can go to complete it because I have another important task to complete.

**Comment by CheaChan** [comment]
Now you can test it maybe it has some errors.

**Comment by nuon-neourng** [comment]
Now form can calculate
