### ISSUE TITLE
[SC0010] Design layout form login

### ISSUE THREAD

**Issue by vuthypouk** [pnc-virtual-company/2018-selection#25]

**Comment by nuon-neourng** [comment]
![capture](https://user-images.githubusercontent.com/37860243/39281868-111d9942-4931-11e8-9c54-a92de2a631bc.PNG)

#Login Form
1. put the logo of application to the form
2. create input username and password

**Comment by dakhen-sok** [comment]
For me I agree with this wire frame, it acceptable for us to develop either.

**Comment by CheaChan** [comment]
Yes it is a good interface, but I just have a few questions:
1/ for the logo you will put on circle or square 
2/ for the option "Do not have an account? sign up" means that all the users can register for this application, so if like that I think our application will not secure. what do you think if we remove this option

**Comment by nuon-neourng** [comment]
To answer b chan question the logo I will put logo of our application and for the question 2 I will cancel it.

**Comment by nuon-neourng** [comment]
![capture](https://user-images.githubusercontent.com/37860243/39283605-37ec7856-4939-11e8-9e40-7cf9c80c5e07.PNG)

this is the new one so we will create a form like this.
