### ISSUE TITLE
[SC017] Form add candidate  -->Student information

### ISSUE THREAD

**Issue by SopheakWEP** [pnc-virtual-company/2018-selection#35]
When we click on add candidate it will open new page

**Comment by CheaChan** [comment]
I will do a research on this task around 2 hours.

**Comment by SopheakWEP** [comment]
2 hours is very long time. Can you do it quickly?

**Comment by CheaChan** [comment]
Yes, I already load a new page, but it is not yet to work with a database.

**Comment by nuon-neourng** [comment]
Good job
