### ISSUE TITLE
[SC024] Residence family status form

### ISSUE THREAD

**Issue by SopheakWEP** [pnc-virtual-company/2018-selection#43]
display from residence family status

**Comment by nuon-neourng** [comment]
this is the requirment
![capture4](https://user-images.githubusercontent.com/37860243/39504361-44938048-4df5-11e8-86a8-3589ec126413.PNG)
this is mine
![capture](https://user-images.githubusercontent.com/37860243/39504365-4b7e7de0-4df5-11e8-9815-d3981d7ec0a8.PNG)
please test it.

**Comment by SopheakWEP** [comment]
for the button Save information in mock-up it on the right not left. can you change button place
