### ISSUE TITLE
[SC026] Analyze Database 

### ISSUE THREAD

**Issue by SopheakWEP** [pnc-virtual-company/2018-selection#45]
The database is very important for this project. we all need to analyze altogether.

**Comment by CheaChan** [comment]
We already analyzed the database yet, and we also validated with our manager for correct. Now we can test it.

**Comment by dakhen-sok** [comment]
For this task we all do it together and we also get the result of this too.On the other hand we also get the advice from our project manager already , so it seem to be good for testing
