### ISSUE TITLE
[ SC011 ] : Edit Form Student

### ISSUE THREAD

**Issue by CheaChan** [pnc-virtual-company/2018-selection#60]

**Comment by CheaChan** [comment]
I have already completed this task, so you can test it to find some mistakes. Now I also waiting for client validation.

**Comment by nuon-neourng** [comment]
it seems to be more complicated. I do not agree yet.

**Comment by SopheakWEP** [comment]
For edit form student I already edited some of the forms and add some forms. So this issue is done
