### ISSUE TITLE
[ SC051 ] Design Databases & Relationship

### ISSUE THREAD

**Issue by CheaChan** [pnc-virtual-company/2018-selection#68]
This morning we need to work on the database after we finished our discussions. We will work on Database Workbench.

**Comment by CheaChan** [comment]
I just finished it in the first step, so maybe it has any mistakes. Please look at the picture. Thank you so much for your work hard.
![selection_committee_db](https://user-images.githubusercontent.com/37863650/39736179-3ba1e886-52a9-11e8-883a-9b1b5723fbf9.png)

**Comment by nuon-neourng** [comment]
For this database is acceptable and it look good.
