### ISSUE TITLE
[SC053]Put background and validate form login

### ISSUE THREAD

**Issue by nuon-neourng** [pnc-virtual-company/2018-selection#70]
The form should be can log in when we type username and password that appear in the database. and choose an appropriate background image to fit with form.

**Comment by dakhen-sok** [comment]
I'll response on this task.

**Comment by dakhen-sok** [comment]
For this task I already did it,but for the problem we need some feedback from our client to know which exactly he want to be with this.even though the background of this form.

**Comment by dakhen-sok** [comment]
however you all can test on it either.

**Comment by CheaChan** [comment]
Yes, it very good for form login I have tested on it already. I just have one question what is the difference when I click on remember me and not click on this.

**Comment by CheaChan** [comment]
Oh, sorry I have a bit confused this task work with a database, but it just a form background.

**Comment by nuon-neourng** [comment]
Well done.
