### ISSUE TITLE
[SC059]Separate menu into Admin user and Normal User

### ISSUE THREAD

**Issue by nuon-neourng** [pnc-virtual-company/2018-selection#85]
for this task you do need to think that, if the role off user admin when we log it will go to page admin and for normal user is the same.

**Comment by dakhen-sok** [comment]
I take this task.

**Comment by dakhen-sok** [comment]
For this task I already finished it.so all of you now can check and test it together.

**Comment by nuon-neourng** [comment]
Perfect.

**Comment by dakhen-sok** [comment]
Ok, thanks. For this one, I think I finished for a long time. So it is time to move it to done section now.
