### ISSUE TITLE
[SC060]Form login with database

### ISSUE THREAD

**Issue by nuon-neourng** [pnc-virtual-company/2018-selection#86]
For this one you need to think about database. It meant that for user that log in into this application they can log in if they have data in the database.

**Comment by dakhen-sok** [comment]
I consider to do this task.

**Comment by dakhen-sok** [comment]
For this task I already finished it.So all of you can go and check it out.

**Comment by dakhen-sok** [comment]
And For this one I already confirm merg. so you can pull from master to check

**Comment by CheaChan** [comment]
Yes, it very good for form login I have tested on it already. I just have one question what is the difference when I click on remember me and not click on this.

**Comment by nuon-neourng** [comment]
it was good
