### ISSUE TITLE
[SC062] Create page coming soon

### ISSUE THREAD

**Issue by nuon-neourng** [pnc-virtual-company/2018-selection#88]
For page that is not complete we need to make client know that it will coming soon.

**Comment by nuon-neourng** [comment]
as all mention the back ground of coming soon page is not so attractive, so now I have change it and look better.

**Comment by dakhen-sok** [comment]
I think that for this task is already finish and I already checked,but what I want you to do is just spend a minute to checkout and change the background.Because I look not so smooth. 
So that's all keep going.
